version: '3'
services:
  zcashd:
    tty: true
    restart: always
    image: hbeckeri/zcashd:1.1.2
    volumes:
     - ./data:/coin/data
     - ./coin.conf:/root/.zcash/zcash.conf
     - ./coin.conf:/coin/data/zcash.conf
    ports:
       - 3000:3000
       - 3001:3001
